# This file was auto-generated by Fern from our API Definition.

import typing

EchelonArmyEchelon = typing.Union[
    typing.Literal[
        "ARMY_ECHELON_INVALID",
        "ARMY_ECHELON_FIRE_TEAM",
        "ARMY_ECHELON_SQUAD",
        "ARMY_ECHELON_PLATOON",
        "ARMY_ECHELON_COMPANY",
        "ARMY_ECHELON_BATTALION",
        "ARMY_ECHELON_REGIMENT",
        "ARMY_ECHELON_BRIGADE",
        "ARMY_ECHELON_DIVISION",
        "ARMY_ECHELON_CORPS",
        "ARMY_ECHELON_ARMY",
    ],
    typing.Any,
]
