# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class EntityIdsSelector(UniversalBaseModel):
    entity_ids: typing_extensions.Annotated[typing.Optional[typing.List[str]], FieldMetadata(alias="entityIds")] = (
        pydantic.Field(default=None)
    )
    """
    Receive tasks as an assignee for one or more of the supplied entity ids.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
