# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .lla_altitude_reference import LlaAltitudeReference


class Lla(UniversalBaseModel):
    lon: typing.Optional[float] = None
    lat: typing.Optional[float] = None
    alt: typing.Optional[float] = None
    is_2_d: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="is2d")] = None
    altitude_reference: typing_extensions.Annotated[
        typing.Optional[LlaAltitudeReference], FieldMetadata(alias="altitudeReference")
    ] = pydantic.Field(default=None)
    """
    Meaning of alt.
     altitude in meters above either WGS84 or EGM96, use altitude_reference to
     determine what zero means.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
