# This file was auto-generated by Fern from our API Definition.

import typing

LlaAltitudeReference = typing.Union[
    typing.Literal[
        "ALTITUDE_REFERENCE_INVALID",
        "ALTITUDE_REFERENCE_HEIGHT_ABOVE_WGS84",
        "ALTITUDE_REFERENCE_HEIGHT_ABOVE_EGM96",
        "ALTITUDE_REFERENCE_UNKNOWN",
        "ALTITUDE_REFERENCE_BAROMETRIC",
        "ALTITUDE_REFERENCE_ABOVE_SEA_FLOOR",
        "ALTITUDE_REFERENCE_BELOW_SEA_SURFACE",
    ],
    typing.Any,
]
