# This file was auto-generated by Fern from our API Definition.

import typing

OrbitMeanElementsMetadataMeanElementTheory = typing.Union[
    typing.Literal["MEAN_ELEMENT_THEORY_INVALID", "MEAN_ELEMENT_THEORY_SGP4"], typing.Any
]
