# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: anduril/tasks/ad/desertguardian/rf/v1/rf_tasks.pub.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class TransmitState(betterproto.Enum):
    INVALID = 0
    TRANSMITTING = 1
    NOT_TRANSMITTING = 2


class SurveillanceState(betterproto.Enum):
    INVALID = 0
    SURVEILLING = 1
    NOT_SURVEILLING = 2


class EmissionControlState(betterproto.Enum):
    INVALID = 0
    ALLOWED = 1
    NOT_ALLOWED = 2


@dataclass(eq=False, repr=False)
class SetTransmitState(betterproto.Message):
    """
    Set the transmit state of an RF Platform such as a Radar, Beacon, or Radio.
    """

    transmit_state: "TransmitState" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class SetSurveillanceState(betterproto.Message):
    """Set the surveillance state of a passive (listen-only) RF Platform."""

    surveillance_state: "SurveillanceState" = betterproto.enum_field(1)


@dataclass(eq=False, repr=False)
class SetEmissionControlState(betterproto.Message):
    """
    Set whether or not an RF Platform has Emmission Control (EmCon).
     If supported, RF platforms should only expose the SetTransmitState task when EmissionControlState is EMISSION_CONTROL_STATE_ALLOWED.
     When in EMISSION_CONTROL_STATE_NOT_ALLOWED, the Platform should be in TRANSMIT_STATE_NOT_TRANSMITTING, and should remove SetTransmitState from the task Catalog.
    """

    emcon_state: "EmissionControlState" = betterproto.enum_field(1)
